export const medicalDiagnoses = [
  "AIDS/HIV",
  "Abdominal aortic aneurysm",
  "Achalasia",
  "Acid reflux",
  "Acne",
  "Acoustic neuroma",
  "Acromegaly",
  "Acute lymphoblastic leukemia (ALL)",
  "Acute lymphocytic leukemia (ALL)",
  "Acute myelogenous leukemia (AML)",
  "Acute myeloid leukemia (AML)",
  "Addison's disease",
  "Adenomyosis",
  "Adhesive capsulitis (frozen shoulder)",
  "Adrenal cancer",
  "Agoraphobia",
  "Alcoholism",
  "Alexander disease",
  "Allergic rhinitis",
  "Allergies",
  "Alopecia areata",
  "Alpha-1 antitrypsin deficiency",
  "Alzheimer's disease",
  "Amebiasis",
  "Amnesia",
  "Amoebiasis",
  "Amphetamine abuse",
  "Amyloidosis",
  "Amyotrophic lateral sclerosis (ALS)",
  "Anal cancer",
  "Anemia",
  "Anencephaly",
  "Angina",
  "Angioedema",
  "Ankylosing spondylitis",
  "Anorexia nervosa",
  "Anthrax",
  "Antiphospholipid syndrome (APS)",
  "Anxiety",
  "Anxiety disorders",
  "Aortic stenosis",
  "Aortic valve stenosis",
  "Apert syndrome",
  "Appendicitis",
  "Apraxia",
  "Argininosuccinic aciduria",
  "Arrhythmia",
  "Arteriosclerosis",
  "Arthritis",
  "Asbestosis",
  "Asthma",
  "Atherosclerosis",
  "Athlete's foot",
  "Atrial fibrillation",
  "Atrial flutter",
  "Auditory processing disorder (APD)",
  "Autism",
  "Autoimmune hepatitis",
  "Autoimmune inner ear disease (AIED)",
  "Autoimmune polyendocrine syndrome (APS)",
  "Autoimmune thrombocytopenic purpura (ATP)",
  "Autonomic neuropathy",
  "Avascular necrosis (osteonecrosis)",
  "Avian flu",
  "Babesiosis",
  "Back pain",
  "Bacterial vaginosis",
  "Balanitis",
  "Barrett's esophagus",
  "Bartonellosis",
  "Bedsores",
  "Bell's palsy",
  "Benign prostatic hyperplasia (BPH)",
  "Bile duct cancer",
  "Bipolar disorder",
  "Bird flu",
  "Birth defects",
  "Black lung disease",
  "Bladder cancer",
  "Bladder stones",
  "Blastoma",
  "Blepharitis",
  "Blindness",
  "Blood clots",
  "Bone cancer",
  "Bone fractures",
  "Botulism",
  "Bowen's disease",
  "Brachial plexus injury",
  "Brain abscess",
  "Brain cancer",
  "Brain injury",
  "Breast Parenchyma Density",
  "Breast cancer",
  "Bronchiectasis",
  "Bronchitis",
  "Brucellosis",
  "Bruises",
  "Bulimia nervosa",
  "Burns",
  "Bursitis",
  "COPD",
  "COPD (Chronic obstructive pulmonary disease)",
  "COVID-19",
  "Caffeine addiction",
  "Cancer",
  "Candidiasis",
  "Candidiasis (yeast infection)",
  "Canker sores",
  "Carbon monoxide poisoning",
  "Cardiac arrest",
  "Cardiomyopathy",
  "Cardiovascular disease (CVD)",
  "Carpal tunnel syndrome",
  "Cataracts",
  "Celiac disease",
  "Cellulitis",
  "Cerebral aneurysm",
  "Cerebral palsy",
  "Cervical cancer",
  "Cervical spondylosis",
  "Chagas disease",
  "Chalazion",
  "Chancroid",
  "Charcot-Marie-Tooth disease",
  "Chickenpox",
  "Chikungunya",
  "Chlamydia",
  "Cholecystitis",
  "Cholera",
  "Cholestasis",
  "Chronic fatigue syndrome",
  "Chronic fatigue syndrome (CFS)",
  "Chronic granulomatous disease (CGD)",
  "Chronic obstructive pulmonary disease (COPD)",
  "Chronic pancreatitis",
  "Cirrhosis",
  "Claudication",
  "Clavus",
  "Cleft lip and palate",
  "Clubfoot",
  "Cluster headaches",
  "Cocaine addiction",
  "Coccidioidomycosis",
  "Cold sores",
  "Colic",
  "Colitis",
  "Colon cancer",
  "Colorectal cancer",
  "Common cold",
  "Compartment syndrome",
  "Complex regional pain syndrome (CRPS)",
  "Concussion",
  "Congenital adrenal hyperplasia (CAH)",
  "Congenital heart disease",
  "Congenital insensitivity to pain (CIP)",
  "Congestive heart failure",
  "Conjunctivitis",
  "Constipation",
  "Contact dermatitis",
  "Conversion disorder",
  "Cornelia de Lange syndrome (CdLS)",
  "Coronary artery disease",
  "Coronary artery disease (CAD)",
  "Cotard delusion",
  "Creutzfeldt-Jakob disease (CJD)",
  "Cri du chat syndrome",
  "Crohn's disease",
  "Croup",
  "Cushing's syndrome",
  "Cystic fibrosis",
  "Cystic fibrosis (CF)",
  "Cysticercosis",
  "Cystitis",
  "Cytomegalovirus (CMV) infection",
  "DVT",
  "Dandy-Walker syndrome",
  "Deep vein thrombosis (DVT)",
  "Dehydration",
  "Dementia",
  "Dengue fever",
  "Dental cavities",
  "Dental health",
  "Depersonalization disorder",
  "Depression",
  "Dermatitis",
  "Developmental coordination disorder (DCD)",
  "Diabetes",
  "Diabetic foot",
  "Diabetic ketoacidosis (DKA)",
  "Diabetic neuropathy",
  "Diabetic retinopathy",
  "Dialysis",
  "Diarrhea",
  "Diffuse large B-cell lymphoma",
  "Digestive system disorders",
  "Diphtheria",
  "Discoid lupus erythematosus",
  "Dissociative identity disorder (DID)",
  "Diverticulitis",
  "Down syndrome",
  "Dracunculiasis",
  "Drowning",
  "Drug abuse",
  "Drug addiction",
  "Drug overdose",
  "Dry eye syndrome",
  "Duchenne muscular dystrophy",
  "Dysentery",
  "Dyslexia",
  "Dysphagia",
  "Dystonia",
  "E. coli infection",
  "Ebola virus disease",
  "Echinococcosis",
  "Eclampsia",
  "Ectodermal dysplasia",
  "Ectopic pregnancy",
  "Eczema",
  "Edwards syndrome",
  "Ehlers-Danlos syndrome (EDS)",
  "Ehrlichiosis",
  "Ejaculation disorders",
  "Electroconvulsive therapy (ECT)",
  "Embolism",
  "Emphysema",
  "Encephalitis",
  "Endocarditis",
  "Endometrial cancer",
  "Endometriosis",
  "Enlarged prostate",
  "Enuresis (bedwetting)",
  "Eosinophilic esophagitis",
  "Ependymoma",
  "Epilepsy",
  "Epiphora (watery eyes)",
  "Epstein-Barr virus (EBV)",
  "Erectile dysfunction",
  "Erectile dysfunction (ED)",
  "Erythema multiforme",
  "Erythromelalgia",
  "Esophageal cancer",
  "Esophageal spasm",
  "Esophagitis",
  "Essential tremor",
  "Excessive sweating",
  "Exercise addiction",
  "Exotropia",
  "Eye disorders",
  "Fabry disease",
  "Facial paralysis",
  "Factor V Leiden",
  "Failed back surgery syndrome (FBSS)",
  "Fanconi anemia",
  "Fatigue",
  "Fatty liver disease",
  "Fecal incontinence",
  "Felty's syndrome",
  "Fibroadenoma",
  "Fibroids",
  "Fibromyalgia",
  "Fifth disease",
  "Filariasis",
  "Fissured tongue",
  "Flat feet (fallen arches)",
  "Flatulence",
  "Flu (Influenza)",
  "Food allergies",
  "Food poisoning",
  "Foot drop",
  "Fragile X syndrome",
  "Fructose malabsorption",
  "Fungal nail infection",
  "G6PD deficiency",
  "GERD (Gastroesophageal reflux disease)",
  "Gallbladder cancer",
  "Gallstones",
  "Gangrene",
  "Gastric cancer",
  "Gastritis",
  "Gastroesophageal reflux disease (GERD)",
  "Gastrointestinal bleeding",
  "Gastrointestinal disorders",
  "Gaucher disease",
  "Genital herpes",
  "Genital warts",
  "Giant cell arteritis",
  "Giardiasis",
  "Gilbert's syndrome",
  "Gingivitis",
  "Glanders",
  "Glaucoma",
  "Glioblastoma",
  "Glioma",
  "Glomerulonephritis",
  "Gluten intolerance",
  "Gonorrhea",
  "Goodpasture syndrome",
  "Gout",
  "Granuloma annulare",
  "Graves' disease",
  "Growth disorders",
  "Guillain-Barré syndrome",
  "Gum disease",
  "Gynecomastia",
  "HIV/AIDS",
  "Hair loss",
  "Hairy cell leukemia",
  "Hallermann-Streiff syndrome",
  "Hallucinations",
  "Hammer toes",
  "Hantavirus pulmonary syndrome",
  "Hashimoto's disease",
  "Hay fever",
  "Head and neck cancer",
  "Headaches",
  "Hearing loss",
  "Heart attack",
  "Heart disease",
  "Heart failure",
  "Heart murmurs",
  "Heart palpitations",
  "Heart valve disease",
  "Heat exhaustion",
  "Heat rash",
  "Heatstroke",
  "Heavy menstrual bleeding (menorrhagia)",
  "Helicobacter pylori infection",
  "Hemangioma",
  "Hematuria",
  "Hemifacial spasm",
  "Hemochromatosis",
  "Hemolytic anemia",
  "Hemophilia",
  "Hemorrhoids",
  "Hepatitis",
  "Hepatitis A",
  "Hepatitis B",
  "Hepatitis C",
  "Hepatitis D",
  "Hepatitis E",
  "Hepatocellular carcinoma",
  "Hepatorenal syndrome (HRS)",
  "Hernia",
  "Heroin addiction",
  "Herpes simplex",
  "Herpes zoster (shingles)",
  "Hiatal hernia",
  "Hiccups",
  "High blood pressure",
  "High cholesterol",
  "Hip dysplasia",
  "Hip fracture",
  "Hirschsprung's disease",
  "Histoplasmosis",
  "Hives",
  "Hodgkin lymphoma",
  "Horner's syndrome",
  "Human papillomavirus (HPV)",
  "Huntington's disease",
  "Hydrocele",
  "Hydrocephalus",
  "Hydronephrosis",
  "Hypercalcemia",
  "Hyperglycemia",
  "Hyperhidrosis",
  "Hyperlipidemia",
  "Hyperparathyroidism",
  "Hypertension",
  "Hypertensive heart disease",
  "Hypertensive retinopathy",
  "Hyperthyroidism",
  "Hypertonia",
  "Hypertrophic cardiomyopathy",
  "Hypertrophic pyloric stenosis",
  "Hypertrophic scarring",
  "Hypoglycemia",
  "Hypoparathyroidism",
  "Hypopituitarism",
  "Hypotension",
  "Hypothermia",
  "Hypothyroidism",
  "Ibuprofen overdose",
  "Ileitis",
  "Ileus",
  "Iliotibial band syndrome (ITBS)",
  "Impetigo",
  "Incontinence",
  "Indigestion",
  "Infant respiratory distress syndrome (IRDS)",
  "Infectious arthritis",
  "Infectious diseases",
  "Infectious mononucleosis",
  "Inflammatory bowel disease (IBD)",
  "Influenza",
  "Influenza (Flu)",
  "Influenza A virus subtype H1N1",
  "Influenza B virus",
  "Influenza C virus",
  "Ingrown toenails",
  "Inguinal hernia",
  "Insect bites and stings",
  "Insomnia",
  "Interstitial cystitis",
  "Interstitial cystitis (IC)",
  "Interstitial lung disease (ILD)",
  "Intestinal obstruction",
  "Intrauterine growth restriction (IUGR)",
  "Iron-deficiency anemia",
  "Irritable bowel syndrome (IBS)",
  "Ischemic colitis",
  "Ischemic heart disease",
  "Itching",
  "Jaundice",
  "Jock itch",
  "Joint pain",
  "Juvenile idiopathic arthritis (JIA)",
  "Kaposi's sarcoma",
  "Kawasaki disease",
  "Keloids",
  "Kidney cancer",
  "Kidney disease",
  "Kidney stones",
  "Klinefelter syndrome",
  "Knee injuries",
  "Knee pain",
  "Korsakoff syndrome",
  "Krabbe disease",
  "Lactose intolerance",
  "Lambert-Eaton myasthenic syndrome (LEMS)",
  "Laryngeal cancer",
  "Laryngitis",
  "Laryngopharyngeal reflux (LPR)",
  "Lassa fever",
  "Latex allergies",
  "Lazy eye (amblyopia)",
  "Lead poisoning",
  "Leg cramps",
  "Legg-Calve-Perthes disease",
  "Leiomyosarcoma",
  "Leishmaniasis",
  "Leprosy",
  "Leptospirosis",
  "Leukemia",
  "Levator Ani Syndrome",
  "Lichen planus",
  "Limb-girdle muscular dystrophy",
  "Lipedema",
  "Lipoma",
  "Lipomas",
  "Liposarcoma",
  "Liver cancer",
  "Liver disease",
  "Liver failure",
  "Liver transplant",
  "Loiasis",
  "Lung cancer",
  "Lung disease",
  "Lung diseases",
  "Lupus",
  "Lyme disease",
  "Lymphedema",
  "Lymphoma",
  "Macular degeneration",
  "Malaria",
  "Male breast cancer",
  "Male infertility",
  "Malignant hyperthermia",
  "Malignant mesothelioma",
  "Marfan syndrome",
  "Mastitis",
  "Measles",
  "Mediterranean fever",
  "Medulloblastoma",
  "Melanoma",
  "Melasma",
  "Memory disorders",
  "Meniere's disease",
  "Meningioma",
  "Meningitis",
  "Menopause",
  "Mental health disorders",
  "Mesothelioma",
  "Metabolic syndrome",
  "Migraine",
  "Mitral regurgitation",
  "Mitral valve prolapse",
  "Molluscum contagiosum",
  "Mononucleosis",
  "Montezuma's revenge (traveler's diarrhea)",
  "Morquio syndrome",
  "Morton's neuroma",
  "Mosquito-borne illnesses",
  "Motion sickness",
  "Motor neurone disease (MND)",
  "Mountain sickness",
  "Multiple myeloma",
  "Multiple sclerosis (MS)",
  "Muscle cramps",
  "Muscle strain",
  "Muscular dystrophy",
  "Myasthenia gravis",
  "Mycoplasma pneumonia",
  "Myelodysplastic syndromes",
  "Myelodysplastic syndromes (MDS)",
  "Myeloma",
  "Myocardial infarction",
  "Myocarditis",
  "Myopia",
  "Myositis",
  "Naegleria infection (primary amoebic meningoencephalitis)",
  "Narcolepsy",
  "National Institute of Mental Health (NIMH)",
  "Neck pain",
  "Neonatal abstinence syndrome (NAS)",
  "Neuroblastoma",
  "Neurofibromatosis",
  "Neurological disorders",
  "Neuroma",
  "Neuromyelitis optica",
  "Neuropathy",
  "Neurosis",
  "Non-Hodgkin lymphoma",
  "Nonalcoholic fatty liver disease (NAFLD)",
  "Nonalcoholic steatohepatitis (NASH)",
  "Norovirus",
  "Norovirus infection",
  "Nosebleed",
  "Nosocomial infections",
  "OCD",
  "Obesity",
  "Obsessive-compulsive disorder (OCD)",
  "Obstructive sleep apnea",
  "Obstructive sleep apnea (OSA)",
  "Occipital neuralgia",
  "Ocular herpes",
  "Opioid addiction",
  "Oral cancer",
  "Oral thrush",
  "Osteoarthritis",
  "Osteogenesis imperfecta (OI)",
  "Osteomalacia",
  "Osteomyelitis",
  "Osteonecrosis",
  "Osteoporosis",
  "Otitis media",
  "Ovarian cancer",
  "Ovarian cysts",
  "Overactive bladder",
  "Overuse injuries",
  "Paget's disease of bone",
  "Painful bladder syndrome",
  "Panic disorder",
  "Papillomavirus infection",
  "Paralysis",
  "Parasitic infections",
  "Parkinson's disease",
  "Paronychia",
  "Parotid gland tumor",
  "Patellofemoral pain syndrome",
  "Patent ductus arteriosus (PDA)",
  "Pelvic inflammatory disease (PID)",
  "Peptic ulcer",
  "Peptic ulcer disease",
  "Pericarditis",
  "Periodontitis",
  "Peripheral artery disease (PAD)",
  "Peripheral neuropathy",
  "Peritonitis",
  "Personality disorders",
  "Pertussis",
  "Pertussis (Whooping cough)",
  "Peyronie's disease",
  "Pharyngitis",
  "Pheochromocytoma",
  "Phobias",
  "Photophobia",
  "Physical injuries",
  "Physical therapy",
  "Piles",
  "Pilonidal cyst",
  "Pituitary gland disorders",
  "Pituitary tumors",
  "Plantar fasciitis",
  "Pleurisy",
  "Pneumonia",
  "Podiatry",
  "Poison ivy rash",
  "Poison ivy, oak, and sumac",
  "Poliomyelitis",
  "Poliomyelitis (Polio)",
  "Polycystic kidney disease",
  "Polycystic ovary syndrome (PCOS)",
  "Polymyalgia rheumatica",
  "Porphyria",
  "Post-concussion syndrome",
  "Post-traumatic stress disorder (PTSD)",
  "Postherpetic neuralgia (PHN)",
  "Postpartum depression",
  "Pott's disease",
  "Prader-Willi syndrome",
  "Preeclampsia",
  "Pregnancy complications",
  "Premature ejaculation",
  "Premenstrual dysphoric disorder (PMDD)",
  "Premenstrual syndrome (PMS)",
  "Presbyopia",
  "Primary biliary cholangitis (PBC)",
  "Primary biliary cirrhosis",
  "Primary lateral sclerosis (PLS)",
  "Primary sclerosing cholangitis",
  "Primary sclerosing cholangitis (PSC)",
  "Progeria",
  "Progressive multifocal leukoencephalopathy (PML)",
  "Progressive supranuclear palsy (PSP)",
  "Prostate cancer",
  "Prostatitis",
  "Psoriasis",
  "Psoriatic arthritis",
  "Psychosis",
  "Pubic lice",
  "Pulmonary embolism",
  "Pulmonary fibrosis",
  "Pulmonary hypertension",
  "Pulmonary sarcoidosis",
  "Pyelonephritis",
  "Q fever",
  "Rabies",
  "Raynaud's disease",
  "Rectal cancer",
  "Rectal prolapse",
  "Reflex sympathetic dystrophy syndrome",
  "Reflux esophagitis",
  "Reiter's syndrome",
  "Relapsing polychondritis",
  "Renal failure",
  "Repetitive strain injuries",
  "Respiratory distress syndrome",
  "Respiratory distress syndrome (RDS)",
  "Respiratory syncytial virus (RSV)",
  "Respiratory syncytial virus (RSV) infection",
  "Restless legs syndrome (RLS)",
  "Retinoblastoma",
  "Rheumatic fever",
  "Rheumatoid arthritis",
  "Rhinitis",
  "Rickets",
  "Ringworm",
  "Rocky Mountain spotted fever",
  "Rocky Mountain spotted fever (RMSF)",
  "Rosacea",
  "Rotator cuff injuries",
  "Rotavirus",
  "Rubella",
  "Rubella (German measles)",
  "SIDS (sudden infant death syndrome)",
  "STDs",
  "Salmonella",
  "Salmonella infection",
  "Salpingitis",
  "Sarcoidosis",
  "Scabies",
  "Scapular dyskinesis",
  "Scarlet fever",
  "Schizophrenia",
  "Sciatica",
  "Scleritis",
  "Scleroderma",
  "Seasonal affective disorder (SAD)",
  "Seborrheic dermatitis",
  "Seizures",
  "Sepsis",
  "Septicemia",
  "Sexually transmitted infections (STIs)",
  "Shigellosis",
  "Shin splints",
  "Shingles",
  "Shock",
  "Sickle cell anemia",
  "Sinus headache",
  "Sinus infections",
  "Sinusitis",
  "Sjogren's syndrome",
  "Sjögren's syndrome",
  "Skin cancer",
  "Sleep apnea",
  "Sleep disorders",
  "Small cell lung cancer",
  "Smallpox",
  "Social anxiety disorder (SAD)",
  "Soft tissue sarcoma",
  "Somatoform disorder",
  "Sore throat",
  "Sotos syndrome",
  "Soy allergy",
  "Spina bifida",
  "Spinal cord injuries",
  "Spinal cord injury",
  "Spinal muscular atrophy",
  "Spinal stenosis",
  "Spondylitis",
  "Spondylolisthesis",
  "Spondylosis",
  "Sporotrichosis",
  "Sprains and strains",
  "Squamous cell carcinoma",
  "Staph infection",
  "Staph infections",
  "Stasis dermatitis",
  "Stomach cancer",
  "Stomach flu",
  "Stomach ulcer",
  "Stomach ulcers",
  "Strabismus",
  "Strep throat",
  "Stress fractures",
  "Stroke",
  "Substance abuse",
  "Sudden infant death syndrome (SIDS)",
  "Suicide",
  "Superficial thrombophlebitis",
  "Superior mesenteric artery syndrome (SMAS)",
  "Supraventricular tachycardia (SVT)",
  "Surgical site infections (SSIs)",
  "Swine flu",
  "Syphilis",
  "Systemic lupus erythematosus (SLE)",
  "Tachycardia",
  "Tardive dyskinesia",
  "Tay-Sachs disease",
  "Tendinitis",
  "Tennis elbow",
  "Tension headache",
  "Tension headaches",
  "Testicular cancer",
  "Testicular torsion",
  "Tetanus",
  "Tethered spinal cord syndrome",
  "Tetracycline staining",
  "Tetralogy of Fallot",
  "Thalassemia",
  "Throat cancer",
  "Thrombocytopenia",
  "Thrombosis",
  "Thyroid cancer",
  "Thyroid disorders",
  "Tinea versicolor",
  "Tinnitus",
  "Toe walking",
  "Tonsillitis",
  "Tooth decay",
  "Topical steroid withdrawal (TSW)",
  "Torticollis",
  "Toxemia",
  "Toxic shock syndrome (TSS)",
  "Toxicity",
  "Toxoplasmosis",
  "Tracheitis",
  "Transient global amnesia (TGA)",
  "Transient ischemic attack (TIA)",
  "Transverse myelitis",
  "Traumatic brain injury (TBI)",
  "Traveler's diarrhea",
  "Trench mouth",
  "Trichinosis",
  "Trichomoniasis",
  "Trigeminal neuralgia",
  "Triple X syndrome",
  "Tuberculosis (TB)",
  "Tularemia",
  "Turner syndrome",
  "Typhoid fever",
  "Ulcerative colitis",
  "Ulcers",
  "Ulnar nerve entrapment",
  "Urinary incontinence",
  "Urinary tract infections (UTIs)",
  "Urticaria",
  "Uterine cancer",
  "Uterine fibroids",
  "Uterine prolapse",
  "Vaginal cancer",
  "Vaginal yeast infection",
  "Varicella (chickenpox)",
  "Varicocele",
  "Varicose veins",
  "Vascular dementia",
  "Vasculitis",
  "Venous insufficiency",
  "Vertigo",
  "Vestibular neuritis",
  "Vitamin B12 deficiency",
  "Vitamin deficiencies",
  "Vitiligo",
  "Vocal cord nodules",
  "Von Hippel-Lindau disease",
  "Von Hippel-Lindau syndrome",
  "Von Willebrand disease",
  "Vulvodynia",
  "Warts",
  "Wegener's granulomatosis",
  "West Nile virus",
  "Whipple's disease",
  "Whooping cough",
  "Wilson's disease",
  "Wolff-Parkinson-White (WPW) syndrome",
  "Yellow fever",
  "Yersiniosis",
  "Zika virus",
  "Zollinger-Ellison syndrome",
];
