import Nav from "./(navigation)/Nav";
import "./globals.css";
import { Roboto } from "next/font/google";

const roboto = Roboto({
  weight: ["400", "500", "700"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${roboto.className}`}>
        <div className="bg-gradient-to-b from-[#ece4de] to-[#e4ddd5]">
          {children}
        </div>
      </body>
    </html>
  );
}
